# Generated by Django 3.2.7 on 2021-10-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_unite_pos7'),
    ]

    operations = [
        migrations.DeleteModel(
            name='unite_pos7',
        ),
    ]
