# Generated by Django 3.2.7 on 2021-10-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_delete_unite_pos7'),
    ]

    operations = [
        migrations.CreateModel(
            name='unite_pos7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(default='admin', max_length=20)),
                ('pos7', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.pos7')),
                ('unite', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.unite')),
            ],
        ),
    ]
