# Generated by Django 3.2.7 on 2021-10-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_unite_pos7'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unite_pos6',
            old_name='added_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='unite_pos7',
            old_name='added_by',
            new_name='user',
        ),
    ]
