# Generated by Django 3.2.7 on 2021-10-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20211012_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runion',
            name='etat',
            field=models.CharField(default='fermé', max_length=20),
        ),
    ]
