# Generated by Django 3.2.7 on 2021-10-21 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_rename_commeriale_unite_commerciale'),
    ]

    operations = [
        migrations.CreateModel(
            name='realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realisation', models.FloatField(blank=True, null=True)),
                ('rempli', models.BooleanField(blank=True, default=False)),
                ('commentaire', models.CharField(blank=True, max_length=256, null=True)),
                ('commentaire_degre', models.IntegerField(blank=True, null=True)),
                ('regler_par', models.CharField(blank=True, max_length=20, null=True)),
                ('monnaie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.monnaie')),
                ('pos6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.pos6')),
                ('pos7', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.pos7')),
                ('pv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.entete_pv')),
            ],
        ),
        migrations.RemoveField(
            model_name='taux_change',
            name='monnaie',
        ),
        migrations.AlterField(
            model_name='proposition',
            name='cloture',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='prevision',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='realisation2',
        ),
        migrations.DeleteModel(
            name='taux_change',
        ),
    ]
