# Generated by Django 3.2.7 on 2021-10-21 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20211021_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(blank=True, max_length=20, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('rempli', models.BooleanField(blank=True, default=False)),
                ('pos6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.pos6')),
                ('pos7', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.pos7')),
                ('pv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.entete_pv')),
            ],
        ),
        migrations.CreateModel(
            name='reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloture', models.FloatField(blank=True, default=0, null=True)),
                ('prevision', models.FloatField(blank=True, default=0, null=True)),
                ('controle_budgetaire', models.FloatField(blank=True, null=True)),
                ('mois_controle', models.CharField(blank=True, max_length=20, null=True)),
                ('date_cadre', models.CharField(blank=True, max_length=20, null=True)),
                ('date_cdd', models.CharField(blank=True, max_length=20, null=True)),
                ('date_sd', models.CharField(blank=True, max_length=20, null=True)),
                ('valide', models.BooleanField(blank=True, default=False)),
                ('cadre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadre', to='budget.profile')),
                ('cdd', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdd', to='budget.profile')),
                ('pos6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.pos6')),
                ('pos7', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.pos7')),
                ('proposition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.proposition')),
                ('pv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.entete_pv')),
                ('realisation_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realisation_1', to='budget.realisation')),
                ('realisation_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realisation_2', to='budget.realisation')),
                ('sd', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd', to='budget.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='reunion_bud',
            name='cadre',
        ),
        migrations.RemoveField(
            model_name='reunion_bud',
            name='cdd',
        ),
        migrations.RemoveField(
            model_name='reunion_bud',
            name='pv',
        ),
        migrations.RemoveField(
            model_name='reunion_bud',
            name='sd',
        ),
        migrations.DeleteModel(
            name='controle_bud',
        ),
        migrations.DeleteModel(
            name='reunion_bud',
        ),
    ]
