# Generated by Django 3.2.7 on 2021-10-21 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20211021_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='modification_mensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_modif', models.CharField(blank=True, max_length=20, null=True)),
                ('janvier', models.FloatField(blank=True, default=0)),
                ('fevrier', models.FloatField(blank=True, default=0)),
                ('mars', models.FloatField(blank=True, default=0)),
                ('avril', models.FloatField(blank=True, default=0)),
                ('mai', models.FloatField(blank=True, default=0)),
                ('juin', models.FloatField(blank=True, default=0)),
                ('juillet', models.FloatField(blank=True, default=0)),
                ('aout', models.FloatField(blank=True, default=0)),
                ('septembre', models.FloatField(blank=True, default=0)),
                ('octobre', models.FloatField(blank=True, default=0)),
                ('novembre', models.FloatField(blank=True, default=0)),
                ('decembre', models.FloatField(blank=True, default=0)),
                ('date_cadre', models.CharField(blank=True, max_length=20, null=True)),
                ('date_cdd', models.CharField(blank=True, max_length=20, null=True)),
                ('date_sd', models.CharField(blank=True, max_length=20, null=True)),
                ('valide', models.BooleanField(blank=True, default=False)),
                ('cadre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadre4', to='budget.profile')),
                ('cdd', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdd4', to='budget.profile')),
                ('pos6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.pos6')),
                ('pos7', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.pos7')),
                ('pv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.entete_pv')),
                ('sd', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd4', to='budget.profile')),
            ],
        ),
        migrations.CreateModel(
            name='modifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_modif', models.CharField(blank=True, max_length=20, null=True)),
                ('modif', models.FloatField(blank=True, default=0)),
                ('date_cadre', models.CharField(blank=True, max_length=20, null=True)),
                ('date_cdd', models.CharField(blank=True, max_length=20, null=True)),
                ('date_sd', models.CharField(blank=True, max_length=20, null=True)),
                ('valide', models.BooleanField(blank=True, default=False)),
                ('cadre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadre3', to='budget.profile')),
                ('cdd', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdd3', to='budget.profile')),
                ('monnaie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.monnaie')),
            ],
        ),
        migrations.CreateModel(
            name='notifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevision', models.FloatField(blank=True, null=True)),
                ('date_cadre', models.CharField(blank=True, max_length=20, null=True)),
                ('date_cdd', models.CharField(blank=True, max_length=20, null=True)),
                ('date_sd', models.CharField(blank=True, max_length=20, null=True)),
                ('valide', models.BooleanField(blank=True, default=False)),
                ('cadre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadre2', to='budget.profile')),
                ('cdd', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdd2', to='budget.profile')),
                ('monnaie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.monnaie')),
                ('pos6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.pos6')),
                ('pos7', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.pos7')),
                ('pv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.entete_pv')),
                ('sd', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd2', to='budget.profile')),
            ],
        ),
        migrations.CreateModel(
            name='notifie_mensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janvier', models.FloatField(blank=True, default=0)),
                ('fevrier', models.FloatField(blank=True, default=0)),
                ('mars', models.FloatField(blank=True, default=0)),
                ('avril', models.FloatField(blank=True, default=0)),
                ('mai', models.FloatField(blank=True, default=0)),
                ('juin', models.FloatField(blank=True, default=0)),
                ('juillet', models.FloatField(blank=True, default=0)),
                ('aout', models.FloatField(blank=True, default=0)),
                ('septembre', models.FloatField(blank=True, default=0)),
                ('octobre', models.FloatField(blank=True, default=0)),
                ('novembre', models.FloatField(blank=True, default=0)),
                ('decembre', models.FloatField(blank=True, default=0)),
                ('date_cadre', models.CharField(blank=True, max_length=20, null=True)),
                ('date_cdd', models.CharField(blank=True, max_length=20, null=True)),
                ('date_sd', models.CharField(blank=True, max_length=20, null=True)),
                ('valide', models.BooleanField(blank=True, default=False)),
                ('cadre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadre1', to='budget.profile')),
                ('cdd', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdd1', to='budget.profile')),
                ('monnaie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.monnaie')),
                ('pos6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.pos6')),
                ('pos7', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.pos7')),
                ('pv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.entete_pv')),
                ('sd', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd1', to='budget.profile')),
            ],
        ),
        migrations.CreateModel(
            name='proposition_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception', models.CharField(blank=True, max_length=30, null=True)),
                ('moyen_reception', models.CharField(blank=True, max_length=30, null=True)),
                ('source_commentaire', models.CharField(blank=True, max_length=256, null=True)),
                ('source_degre', models.IntegerField(blank=True, null=True)),
                ('pv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.entete_pv')),
            ],
        ),
        migrations.RemoveField(
            model_name='modification',
            name='cadre',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='cdd',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='pv',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='sd',
        ),
        migrations.RemoveField(
            model_name='notifie_bud',
            name='cadre',
        ),
        migrations.RemoveField(
            model_name='notifie_bud',
            name='cdd',
        ),
        migrations.RemoveField(
            model_name='notifie_bud',
            name='modification',
        ),
        migrations.RemoveField(
            model_name='notifie_bud',
            name='pv',
        ),
        migrations.RemoveField(
            model_name='notifie_bud',
            name='sd',
        ),
        migrations.RemoveField(
            model_name='notifie_bud_m',
            name='cadre',
        ),
        migrations.RemoveField(
            model_name='notifie_bud_m',
            name='cdd',
        ),
        migrations.RemoveField(
            model_name='notifie_bud_m',
            name='pv',
        ),
        migrations.RemoveField(
            model_name='notifie_bud_m',
            name='sd',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='date_reception',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='moyen_reception',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='source_commentaire',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='source_degre',
        ),
        migrations.DeleteModel(
            name='historique_modification',
        ),
        migrations.DeleteModel(
            name='modification',
        ),
        migrations.DeleteModel(
            name='notifie_bud',
        ),
        migrations.DeleteModel(
            name='notifie_bud_m',
        ),
        migrations.AddField(
            model_name='modifications',
            name='notifie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.notifie'),
        ),
        migrations.AddField(
            model_name='modifications',
            name='pos6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.pos6'),
        ),
        migrations.AddField(
            model_name='modifications',
            name='pos7',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.pos7'),
        ),
        migrations.AddField(
            model_name='modifications',
            name='pv',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.entete_pv'),
        ),
        migrations.AddField(
            model_name='modifications',
            name='sd',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd3', to='budget.profile'),
        ),
    ]
